// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************

import 'package:ff_annotation_route/ff_annotation_route.dart';
import 'package:flutter/widgets.dart';
import 'pages/complex/home_page.dart';
import 'pages/main_page.dart';
import 'pages/simple/pinned_box.dart';
import 'pages/simple/pinned_header.dart';
import 'pages/simple/sliver_app_bar.dart';

RouteResult getRouteResult({String name, Map<String, dynamic> arguments}) {
  arguments = arguments ?? const <String, dynamic>{};
  switch (name) {
    case 'fluttercandies://PinnedBox':
      return RouteResult(
        name: name,
        widget: PinnedBox(),
        routeName: 'PinnedBox',
        description: 'simple pinned box.',
        exts: <String, dynamic>{'group': 'Simple', 'order': 1},
      );
    case 'fluttercandies://PinnedHeader':
      return RouteResult(
        name: name,
        widget: PinnedHeader(),
        routeName: 'PinnedHeader',
        description: 'pinned header without minExtent and maxExtent.',
        exts: <String, dynamic>{'group': 'Simple', 'order': 0},
      );
    case 'fluttercandies://demogrouppage':
      return RouteResult(
        name: name,
        widget: DemoGroupPage(
          keyValue:
              arguments['keyValue'] as MapEntry<String, List<DemoRouteResult>>,
        ),
        routeName: 'DemoGroupPage',
      );
    case 'fluttercandies://homePage':
      return RouteResult(
        name: name,
        widget: HomePage(),
        routeName: 'HomePage',
        description: 'A complex demo with extended_sliver.',
        exts: <String, dynamic>{'group': 'Complex', 'order': 0},
      );
    case 'fluttercandies://mainpage':
      return RouteResult(
        name: name,
        widget: MainPage(),
        routeName: 'MainPage',
      );
    case 'fluttercandies://sliverAppbar':
      return RouteResult(
        name: name,
        widget: SliverAppbarDemo(),
        routeName: 'SliverAppbar',
        description: 'extended SliverAppbar.',
        exts: <String, dynamic>{'group': 'Simple', 'order': 2},
      );
    default:
      return const RouteResult(name: 'flutterCandies://notfound');
  }
}

class RouteResult {
  const RouteResult({
    @required this.name,
    this.widget,
    this.showStatusBar = true,
    this.routeName = '',
    this.pageRouteType,
    this.description = '',
    this.exts,
  });

  /// The name of the route (e.g., "/settings").
  ///
  /// If null, the route is anonymous.
  final String name;

  /// The Widget return base on route
  final Widget widget;

  /// Whether show this route with status bar.
  final bool showStatusBar;

  /// The route name to track page
  final String routeName;

  /// The type of page route
  final PageRouteType pageRouteType;

  /// The description of route
  final String description;

  /// The extend arguments
  final Map<String, dynamic> exts;
}
