// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
const List<String> routeNames = <String>[
  'fluttercandies://PinnedBox',
  'fluttercandies://PinnedHeader',
  'fluttercandies://demogrouppage',
  'fluttercandies://mainpage',
  'fluttercandies://personalPage',
];

class Routes {
  const Routes._();

  /// 'simple pinned box.'
  ///
  /// [name] : 'fluttercandies://PinnedBox'
  ///
  /// [routeName] : 'PinnedBox'
  ///
  /// [description] : 'simple pinned box.'
  ///
  /// [exts] : {group: Simple, order: 1}
  static const String fluttercandiesPinnedBox = 'fluttercandies://PinnedBox';

  /// 'pinned header without minExtent and maxExtent.'
  ///
  /// [name] : 'fluttercandies://PinnedHeader'
  ///
  /// [routeName] : 'PinnedHeader'
  ///
  /// [description] : 'pinned header without minExtent and maxExtent.'
  ///
  /// [exts] : {group: Simple, order: 0}
  static const String fluttercandiesPinnedHeader =
      'fluttercandies://PinnedHeader';

  /// 'DemoGroupPage'
  ///
  /// [name] : 'fluttercandies://demogrouppage'
  ///
  /// [routeName] : 'DemoGroupPage'
  ///
  /// [arguments] : [keyValue]
  ///
  /// [argumentTypes] : [List<DemoRouteResult>]
  static const String fluttercandiesDemogrouppage =
      'fluttercandies://demogrouppage';

  /// 'MainPage'
  ///
  /// [name] : 'fluttercandies://mainpage'
  ///
  /// [routeName] : 'MainPage'
  static const String fluttercandiesMainpage = 'fluttercandies://mainpage';

  /// 'how to use extended_sliver in '
  ///
  /// [name] : 'fluttercandies://personalPage'
  ///
  /// [routeName] : 'personal'
  ///
  /// [description] : 'how to use extended_sliver in '
  ///
  /// [exts] : {group: Complex, order: 0}
  static const String fluttercandiesPersonalPage =
      'fluttercandies://personalPage';
}
