// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
const List<String> routeNames = <String>[
  'fluttercandies://PinnedBox',
  'fluttercandies://PinnedHeader',
  'fluttercandies://demogrouppage',
  'fluttercandies://homePage',
  'fluttercandies://mainpage',
  'fluttercandies://sliverAppbar',
];

class Routes {
  const Routes._();

  /// 'simple pinned box.'
  ///
  /// [name] : 'fluttercandies://PinnedBox'
  ///
  /// [routeName] : 'PinnedBox'
  ///
  /// [description] : 'simple pinned box.'
  ///
  /// [exts] : {group: Simple, order: 1}
  static const String fluttercandiesPinnedBox = 'fluttercandies://PinnedBox';

  /// 'pinned header without minExtent and maxExtent.'
  ///
  /// [name] : 'fluttercandies://PinnedHeader'
  ///
  /// [routeName] : 'PinnedHeader'
  ///
  /// [description] : 'pinned header without minExtent and maxExtent.'
  ///
  /// [exts] : {group: Simple, order: 0}
  static const String fluttercandiesPinnedHeader =
      'fluttercandies://PinnedHeader';

  /// 'DemoGroupPage'
  ///
  /// [name] : 'fluttercandies://demogrouppage'
  ///
  /// [routeName] : 'DemoGroupPage'
  ///
  /// [constructors] :
  ///
  /// DemoGroupPage : [MapEntry<String, List<DemoRouteResult>> keyValue]
  static const String fluttercandiesDemogrouppage =
      'fluttercandies://demogrouppage';

  /// 'A complex demo with extended_sliver.'
  ///
  /// [name] : 'fluttercandies://homePage'
  ///
  /// [routeName] : 'HomePage'
  ///
  /// [description] : 'A complex demo with extended_sliver.'
  ///
  /// [exts] : {group: Complex, order: 0}
  static const String fluttercandiesHomePage = 'fluttercandies://homePage';

  /// 'MainPage'
  ///
  /// [name] : 'fluttercandies://mainpage'
  ///
  /// [routeName] : 'MainPage'
  ///
  /// [constructors] :
  ///
  /// MainPage : []
  static const String fluttercandiesMainpage = 'fluttercandies://mainpage';

  /// 'extended SliverAppbar.'
  ///
  /// [name] : 'fluttercandies://sliverAppbar'
  ///
  /// [routeName] : 'SliverAppbar'
  ///
  /// [description] : 'extended SliverAppbar.'
  ///
  /// [exts] : {group: Simple, order: 2}
  static const String fluttercandiesSliverAppbar =
      'fluttercandies://sliverAppbar';
}
