// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************

import 'package:ff_annotation_route_library/ff_annotation_route_library.dart';
import 'package:flutter/widgets.dart';
import 'pages/complex/home_page.dart';
import 'pages/main_page.dart';
import 'pages/simple/pinned_box.dart';
import 'pages/simple/pinned_header.dart';
import 'pages/simple/sliver_app_bar.dart';

// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import
FFRouteSettings getRouteSettings({
  required String name,
  Map<String, dynamic>? arguments,
  Widget? notFoundWidget,
}) {
  final Map<String, dynamic> safeArguments =
      arguments ?? const <String, dynamic>{};
  switch (name) {
    case 'fluttercandies://PinnedBox':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        widget: PinnedBox(),
        routeName: 'PinnedBox',
        description: 'simple pinned box.',
        exts: <String, dynamic>{'group': 'Simple', 'order': 1},
      );
    case 'fluttercandies://PinnedHeader':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        widget: PinnedHeader(),
        routeName: 'PinnedHeader',
        description: 'pinned header without minExtent and maxExtent.',
        exts: <String, dynamic>{'group': 'Simple', 'order': 0},
      );
    case 'fluttercandies://demogrouppage':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        widget: DemoGroupPage(
          keyValue: asT<MapEntry<String, List<DemoRouteResult>>>(
              safeArguments['keyValue'])!,
        ),
        routeName: 'DemoGroupPage',
      );
    case 'fluttercandies://homePage':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        widget: HomePage(),
        routeName: 'HomePage',
        description: 'A complex demo with extended_sliver.',
        exts: <String, dynamic>{'group': 'Complex', 'order': 0},
      );
    case 'fluttercandies://mainpage':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        widget: MainPage(),
        routeName: 'MainPage',
      );
    case 'fluttercandies://sliverAppbar':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        widget: SliverAppbarDemo(),
        routeName: 'SliverAppbar',
        description: 'extended SliverAppbar.',
        exts: <String, dynamic>{'group': 'Simple', 'order': 2},
      );
    default:
      return FFRouteSettings(
        name: '404',
        routeName: '404_page',
        widget: notFoundWidget,
      );
  }
}
